#!/bin/bash

echo "SAHAYA Platform - Quick Start Guide"
echo "======================================"
echo ""
echo "Platform is running on: http://localhost:3000"
echo ""
echo "Quick Access Links:"
echo ""
echo "START HERE - Platform Overview:"
echo "   → http://localhost:3000/features.html"
echo ""
echo "User Features:"
echo "   → Home Page: http://localhost:3000/index.html"
echo "   → Sign Up: http://localhost:3000/user-signup.html"
echo "   → Login: http://localhost:3000/user-login.html"
echo "   → Find Services: http://localhost:3000/find-service.html"
echo "   → My Bookings: http://localhost:3000/my-bookings.html"
echo "   → Payment: http://localhost:3000/payment.html"
echo "   → Reviews: http://localhost:3000/reviews-page.html"
echo "   → Give Review: http://localhost:3000/give-review.html"
echo "   → Saved Professionals: http://localhost:3000/saved-professionals.html"
echo "   → Chat: http://localhost:3000/chat.html"
echo "   → Settings: http://localhost:3000/profile-settings.html"
echo ""
echo "Provider Features:"
echo "   → Sign Up: http://localhost:3000/provider-signup.html"
echo "   → Login: http://localhost:3000/provider-login.html"
echo "   → Dashboard: http://localhost:3000/dashboard2.html"
echo "   → Earnings: http://localhost:3000/provider-earnings.html"
echo ""
echo "Admin Features:"
echo "   → Admin Login: http://localhost:3000/admin-login.html"
echo "   → Password: SAHO9"
echo "   → Dashboard: http://localhost:3000/admin-panel.html"
echo ""
echo "Design Features:"
echo "   • Royal Blue: #4169E1"
echo "   • Moonlight: #E0E6FF, #D0D8F4"
echo "   • Glassmorphism effects"
echo "   • Fully responsive"
echo ""
echo "Platform Statistics:"
echo "   • 26 Pages"
echo "   • 25+ Services"
echo "   • 20+ API Endpoints"
echo "   • 11 Database Tables"
echo "   • 3 User Types (User/Provider/Admin)"
echo ""
echo "To stop the server:"
echo "   • Press Ctrl+C in the terminal"
echo ""
echo "Development Tip:"
echo "   • Open browser DevTools (F12) to see console logs"
echo "   • Check Network tab to monitor API calls"
echo "   • Use Application tab to see localStorage tokens"
echo ""
echo "VISIT AGAIN"
echo "======================================"
